### ISSUE TITLE
Consider onboarding

### ISSUE THREAD

**Issue by Bird-Eye** [silvernode/voidbuilds#6]
https://infradocs.voidlinux.org/org/onboarding.html

**Comment by Bird-Eye** [comment]
Void is missing what you provide. Installable single-desktop images. You should join Void TM. Granted, you can keep building independently but more transparency is desirable.  As a matter of fact all 3 issues revolve around the same paradigm: trust.

**Comment by silvernode** [comment]
It's a good idea but not one that I was ever planning on making. I originally was not even going to make this project public but figured I might as well. That being said, getting more serious with the project is simply beyond the scope of the effort that I desire to put in. I never wanted this to be a super big deal or some official partnership of any kind. My code probably wouldn't meet the standards of real developers anyway. I'm just a hobbyist that decided to mess around with stuff. 

Thank you for writing in though and caring at all about the project. 
I forgot to archive this repo a long time ago when I created a voidbuilds project user on Github which is where the real development happens.  

[Main Repo Here](https://github.com/void-builds/void-mklive)
